baseurl = "https://blog.raduciurca.com"
title = "Going Further"
author = "Radu Ciurca"
canonifyurls = true
paginate = 3
theme = "aether"
googleAnalytics = "UA-159982567-1"
#disqusShortname = "ciurca"
[params]
brand = "Going Further"
description = "Radu Ciurca's blog"
bgimg = "img/ignasi_pattern_s.png"
addThis = "ra-5e90518156180de3"

