baseurl = "https://blog.raduciurca.com"
title = "Going Further"
author = "Radu Ciurca"
descritpion = "Radu Ciurca - Going Further - Blog, Essays and Posts 
canonifyurls = true
paginate = 3
theme = "aether"
googleAnalytics = "UA-159982567-1"
enableRobotsTXT = true
#disqusShortname = "ciurca"
[params]
brand = "Going Further"
description = "Radu Ciurca's blog"
bgimg = "img/ignasi_pattern_s.png"

