baseurl = "https://blog.raduciurca.com"
title = "Going Further"
author = "Radu Ciurca"
canonifyurls = true
paginate = 3
theme = "aether"
googleAnalytics = "UA-159982567-1"
enableRobotsTXT = true
#disqusShortname = "ciurca"
[params]
brand = "Going Further"
description = "Radu Ciurca - Going Further - Blog, Essays and Posts"
keywords:
  - Going Further
  - blog
  - Radu Ciurca
  - essays
  - Radu Ciurca blog
  - Radu Ciurca Going Further
  - Going Further Radu Ciurca
bgimg = "img/ignasi_pattern_s.png"
